### ISSUE TITLE
Julia 1.5 and higher will work this way by default

### ISSUE THREAD

**Issue by garrison** [jw3126/EponymKeywordSyntax.jl#3]
Just noting here that this package will no longer be necessary as of julia 1.5 now that JuliaLang/julia#34331 is merged.  It will still be useful to have on older versions of julia, though.

**Comment by jw3126** [comment]
Good point thanks! A PR with a depwarn on 1.5 would be welcome.

**Comment by garrison** [comment]
When I filed this issue, I thought it might actually be better just to update the README and have the code do nothing on versions 1.5 and higher.  This way, somebody can have a package that relies on it while working on both julia 1.0 and 1.5, and there is not a constant (annoying) warning when running under 1.5.

Even better, I suppose (but I am not certain it is worth the effort) would be to integrate this feature into Compat.jl, since it is a package that exists exactly for cross-version compatibility, using the macro you provided as a starting point.  There may be some tweaking required to get the semantics to match exactly.  Then the current package could warn on *all* versions of julia that it is deprecated and that people are encouraged to use Compat instead if they need compatibility on julia versions prior to 1.5.

Again, I think this would make much more sense, but just adding a note to the README would be a good first step for now.  Perhaps a second step would be to file an issue with Compat pointing here, in case anybody wants to use it as a starting point for integrating the functionality there.

**Comment by jw3126** [comment]
Sounds good, I added a note to the README

**Comment by garrison** [comment]
And I opened https://github.com/JuliaLang/Compat.jl/issues/699

**Comment by omus** [comment]
Included in Compat.jl as of version 3.32.0

**Comment by garrison** [comment]
Great!

> Then the current package could warn on _all_ versions of julia that it is deprecated and that people are encouraged to use Compat instead if they need compatibility on julia versions prior to 1.5.

I suppose this is the only thing left to do then before closing this issue -- if someone is motivated enough.
